### ISSUE TITLE
Rethink the project naming?

### ISSUE THREAD

**Issue by Mx-Glitter** [fansible/composer#3]
Currently, the naming may cause confusion as it is the same as [https://github.com/composer/composer](composer) own project.

We should find a better naming for it, ideally one that makes it understand immediately what it's about, e.g. something like `symfony-ansible-provisionning`. WDYT?

**Comment by kosssi** [comment]
Je suis d'accord avec toi

**Comment by MaximeThoonsen** [comment]
@Triiistan  +1000 all suggestions are welcome =)
